In [14]:
from pymongo import MongoClient
import pandas as pd

client = MongoClient(
    "mongodb://root:admin@mongo:27017/",
    authSource="admin"
)

db   = client['rta_project']
coll = db['lyft_status']

cursor = coll.find().sort("_id", -1).limit(1000)
df = pd.DataFrame(list(cursor))

df.head(10)

,_id,station_id,bikes_available,docks_available,last_reported,collected_at
0,681e255dee2ddc903185eee6,b6a13f2b-deb4-4f4d-9d67-7d23bee27c88,6,8,1746806028,2025-05-09T15:55:09.095706
1,681e255dee2ddc903185eee5,66ddd8a8-0aca-11e7-82f6-3863bb44ef7c,9,5,1746806028,2025-05-09T15:55:09.095706
2,681e255dee2ddc903185eee4,5faf99b8-9046-450f-9d2a-d13279b3d016,23,8,1746806025,2025-05-09T15:55:09.095706
3,681e255dee2ddc903185eee3,5aa81a37-ea1d-4bf6-ab40-4751c6b4fb08,0,17,1746806019,2025-05-09T15:55:09.095706
4,681e255dee2ddc903185eee2,66ddd93e-0aca-11e7-82f6-3863bb44ef7c,10,3,1746806018,2025-05-09T15:55:09.095706
5,681e255dee2ddc903185eee1,66dddc08-0aca-11e7-82f6-3863bb44ef7c,5,9,1746806010,2025-05-09T15:55:09.095706
6,681e255dee2ddc903185eee0,46813ecf-8df4-4c8f-9579-0179e0b36ba6,10,8,1746806004,2025-05-09T15:55:09.095706
7,681e255dee2ddc903185eedf,519824e4-69ba-4270-a395-17c204f328f8,4,14,1746805981,2025-05-09T15:55:09.095706
8,681e255dee2ddc903185eede,9d344652-976b-4c2d-bede-2ef19b0fbf13,10,8,1746805951,2025-05-09T15:55:09.095706
9,681e255dee2ddc903185eedd,581211b2-4e42-48f2-8a8f-5f968cb1c5df,28,4,1746805941,2025-05-09T15:55:09.095706

In [16]:
from pymongo import MongoClient

client = MongoClient("mongodb://root:admin@mongo:27017/", authSource="admin")
coll   = client['rta_project']['lyft_status']


total = coll.count_documents({})
print("Łącznie dokumentów:", total)


unique = len(coll.distinct('station_id'))
print("Unikalnych station_id:", unique)

Łącznie dokumentów: 37978
Unikalnych station_id: 2234